# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  _<h3>Thanks for reaching here <3.. Please give my profile a star and to become galaxies together ğŸŒŒ</h3>_
  
  <img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZThycXJ3dGgzejVlMzlmeHR2djM2cDE4MHluOTJyY3UwbjdoMXN2YSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8Z8Zzm68kKrMUAQyOl/giphy.gif" width="40%">
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  _<h3>Nice try nice try ğŸ’œğŸ’›ğŸ’šğŸ’™</h3>_
  
  <img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3BuMW5wNXVuc3AzYTd0NGJicndkcGl0dm56MG01NHVjcHA3OXQ3cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Hc9hdbbyq6m9a/giphy.gif" width="40%">
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  _<h3>Congrats on merging your 1st long arm ğŸŒšğŸ‰ğŸŒ</h3>_
  
  <img src="https://tenor.com/view/guarimba-bouncing-woman-big-boobs-wrong-bra-gif-16842151" width="40%">
# It is recommended to include as many gifs and emojis as possible!
