settings:
  username: "t1noo7"
  commit_msg: "âš¡Ù©(Ì¾â—Ì®Ì®ÌƒÌ¾â€¢ÌƒÌ¾)Û¶ğŸ”¥ à¹“ğ”¸ğ’½ Ò“ğ“›â“„ğ“Œ ğ”Ïğ”¡ï½ğ“½áµ‰â™§ ğŸ˜¡ğŸ”¥Ù©(Ì¾â—Ì®Ì®ÌƒÌ¾â€¢ÌƒÌ¾)Û¶âš¡"
  max_lines: 0
  readme_file: "README.md"
  disabled_events: [event1, event2, event3]
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+07:00"
    text: "<i>Last refresh</i> : <b>{DATE}</b>"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "Kakarotto-bot"
  commit_email: "179298795+Kakarotto-bot@users.noreply.github.com"
